version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"

    env_file:
      - .env
    
    working_dir: /app

    image: my-t3-todos-app
    ports:
      - 3000:3000

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y

  migrator:
    build:
      context: .
      dockerfile: MigratorDockerfile
    image: my-t3-todos-app-db-migrator
    env_file:
      - .env
    restart: "no"
    depends_on:
      - db
    entrypoint: ["npx", "--yes", "prisma", "migrate", "deploy"]